chapters/kirovohrad.json
Kirovohrad NodeSchool chapter.
=> Add kirovohrad chapter

chapters/campinas.json
Adding @edersonnascimento as an organiser of the Campinas team. :)
Though the change is very small, I prefer to wait for a review, since it affects the website directly.
=> Adding one more organiser to the Campinas team

languages/id.json
Hi @finnp, found some missing translation's strings.
cheers!
Khal
=> Added missing translations

chapters/bali.json
please add in this json file so out chapter becomes visable on the main site.  we have already added the sticker directly to the main repo (sorry for that, we will do pull requests instead for the future.)
=> Created bali.json

chapters/bali.json, hexdex.html
Add bali's sticker into the hexdex.html Merge pull request #198 from LaughingSun/master  :)
=> Add bali's sticker into the hexdex.html Merge pull request #198 from LaughingSun/master

chapters/list.json
do I need to do a PR for dependencies.js as well?
=> added Bali chapter by doing npm run build

chapters/sanfrancisco.json
Before merging. I'd like to get at least one :+1: from @llkats or @duquet.
:sparkles:Yay!:sparkles:
=> Add sf to the chapters directory

chapters/list.json
Add Portland and SF chapters and compile said chapters
=> compile chapters!

index.html, languages/ru.json
Add learn-generators workshopper to the list.
But, should it be ES6 or ES2015 or ... Generators workshopper?
=> index: add learn-generators workshopper

chapters/madrid.json
We are in the process of creating the Madrid chapter, please help us be discovered!
=> New Madrid chapter.

index.html
how-to-npm learning module is written by the creator of npm, Isaac. I am just opening a PR to add it to 'Electives'
=> Add how-to-npm to workshoppers

chapters/list.json, chapters/manizales.json
=> Created Manizales chapter

host.html
see https://github.com/nodeschool/discussions/issues/247
=> adding link to coc dot com

languages/ja.json
Hi, I added a ja description to `how-to-npm`.
=> Added a ja description to how-to-npm

chapters/fort-lauderdale.json, chapters/list.json, chapters/miami.json
Hey guys!
This pull request adds chapter JSON files for the Miami and Fort Lauderdale chapters.
I've also run the `npm run build` command to update `chapters/list.json` after I've added the chapter JSON files.
Thanks a million to everybody lending a hand to NodeSchool!
=> Add Miami and Fort Lauderdale chapters

chapters/list.json, chapters/medellin.json
=> Add Medellín chapter

js/main.js
`boxContainer` and `back` are defined but `boxContainer` is never used. (The only line where anything happens is commented out.) And `back` gets manipulated but never appended to the DOM. (That's the commented out line.)
=> Remove dead code

host.html
Our experiences in the first gathering of the Madrid chapter.
=> Added Madrid post-mortem.

chapters/bogota.json
=> adding bogota.json

chapters/list.json, chapters/lodz.json
I added ```lodz.json``` file and run ```npm run build```. I wonder why there are changes in ```list.json``` which I didn't make.
=> Add NodeSchool Lodz to the list of chapters

style.css
Hey,
this PR fixes a few contrast issues with the current web page. See http://wave.webaim.org/report#/http://nodeschool.io for a report. It basically just makes a few greys a bit darker.
Best,
Finn
=> Fix contrast issues

index.html, languages/de.json
Hey,
I started a workshopper for learning to test code a while ago. I just reviewed it again and wanted to make it public on the website. There could still be more exercises, but I think it's already a good workshop. And I would love to get more feedback about it.
Best,
Finn
=> Add test-anything workshopper

languages/ja.json
=> Update chapters-header on ja.json

languages/ja.json
@martinheidegger 
Sorry my bad.
https://github.com/nodeschool/nodeschool.github.io/pull/280
=> fix ja.json

chapters/hanoi.json
https://github.com/nodeschool/hanoi/tree/gh-pages
=> Adding Hanoi Chapter

chapters/santiago.json
I left a collaborator to add the pull request and he pushed changes to Master.
Here's the pull request to add the location.
=> adding Santiago SCL as a chapter 

chapters/list.json
Sorry for missing the build operation.
=> Compiled chapter list

chapters/chiangmai.json
Added in the chapter for Chiang Mai
=> Chiang Mai

chapters/seville.json
New location for NodeSchool International Day.
=> Adding new location: Seville

chapters/belgrade.json
Add NodeSchool Belgrade to chapters as requested in step 5 of organizers guide: https://github.com/nodeschool/organizers#5.
=> Add NodeSchool Belgrade to chapters.

about.html
The h2 header has too much top padding: it should be h3, like all the others.
=> Fix header

building-workshops.html, host.html
Related to #308, there is too much padding in the h2, but it looks fine as h3.
=> Fix all h2 headers on all pages

chapters/western_mass.json
Should close https://github.com/nodeschool/western-mass/issues/13
Would expect @Sequoia and @a-pasquale to confirm this is correct info.
=> Add western mass chapter

chapters/list.json
oops the commit message is crazy cuz I started typing before commit was done :p
=> built for western-mass but it looks like many chapters missed

chapters/list.json, chapters/pereira.json
I just added the chapter file for our city.
~~Not sure if should I include the builded file or not, I include it~~
=> Added Pereira chapter to the website

chapters.html
=> fix typo on chapters page

chapters/edmonton.json, chapters/list.json
Add edmonton chapter. Ran build to update list.
=> add edmonton chapter

chapters/list.json, chapters/utrecht.json
Hi all,
Here's a pull request for a new nodeschool chapter
Fritz
=> add utrecht info

index.html
See https://github.com/bevacqua/perfschool
=> Add perfschool workshopper to electives

chapters/cochabamba.json
Archivo de Configuración de los datos del Evento NodeSchool Cochabamba
=> Added cochabamba.json

chapters/zagreb.json
I've mistakenly pushed to this repo because it seems I have access, reverted back to previous commit and then force pushed again immediately. Sorry about that :disappointed:
=> add zagreb to chapters

chapters/hyderabad.json
=> Added hyderabad.json

index.html
I feel this is a core part of the JS language, and should sit with the other
workshops there. But I could be entirely wrong, so feel free to move it if you
like :)
=> Add Scope Chains & Closures workshopper

index.html
see https://github.com/mmckegg/web-audio-school
=> add web-audio-school workshopper

languages/de.json, languages/ko.json, languages/tr.json, style.css
=> Remove international day

chapters/santiago.json
=> Move Santiago to Latin America region

index.html, js/index.js
change markup & selectors in script.
Related to discussion in https://github.com/nodeschool/nodeschool.github.io/pull/338
=> Change google analytics events for workshop links

chapters/heidelberg.json
This will add the Heidelberg Chapter :+1:
=> Add Heidelberg Chapter

chapters/cincinnati.json
Adds Cincinnati to the list of chapters.
=> adds cincinnati

chapters/anchorage.json
Adds anchorage.json to the /Chapters directory.
=> Add Anchorage Chapter JSON

chapters/hcmc-saigon.json
Hi here is our twitter info on the json file =)
=> Added twitter user info

chapters/usac.json
Add Usac.json chapter description, site already tested locally
@cruzperez pull request with a single commit :)
closes https://github.com/nodeschool/usac.gt/issues/3
=> Add USAC, Guatemala City Chapter

index.html
a new workshop about using regular expressions in javascript
=> regex adventure workshop

index.html
As per https://github.com/nodeschool/workshoppers/issues/34 from @maxogden
This is adds to the bottom of the elective list.
=> Adding torrential a bittorrent workshop

languages/pt-br.json
Adding translations for new "mentor at event" page.
Fixes #397 .
=> Translating mentor at event page to pt-br.

index.html
It seems makemehapi has been moved to https://github.com/hapijs/makemehapi
=> fix broken link -> makemehapi

chapters/iem-kolkata.json
Add IEM Kolkata Chapter file : https://github.com/nodeschool/iem-kolkata
=> Add IEM Kolkata Chapter file

chapters/washingtondc.json
/cc @danmactough @adunkman @joshfinnie
=> Add Washington DC chapter.

chapters/augsburg.json, chapters/munich.json
Sorry, we forgot one developer :)
=> Updated organizers for munich and augsburg

chapters/chernivtsi.json
Hey! I've added **Chernivtsi** chapter!
Look at this [organizers#269](https://github.com/nodeschool/organizers/issues/269).
=> Add Nodeschool Chernivtsi.

index.html, languages/fr-fr.json
Another React workshopper!
This one has been around for a while and has recently been updated to use the latest version of React and associated best practices. It is quite an interesting take on the workshopper format because it is based on an online tutorial (https://facebook.github.io/react/docs/thinking-in-react.html), and integrates browser rendering of the solutions so that you can see what you're building.
It also makes a very cool use of [blessed](https://github.com/chjj/blessed) for some levels: 
Disclaimer: I'm not the workshopper's author, but he's [very happy](https://github.com/asbjornenge/thinking-in-react/pull/14#issuecomment-142249724) to have it integrated here.
=> Add Thinking in React workshopper

chapters/philadelphia.json
Added the Nodeschool Philadelphia chapter json file
=> Nodeschool Philadelphia Chapter File

events.css, js/table.js, style.css
*Updates:*
- list of languages
- navigations lists
- calendar of events
- containers paddings for small width devices
Before:
After:
=> Fix layout of lists, events table on mobile devices

chapters/madison.json
This pull request is to add the Nodeschool Madison chapter to the chapters list.
=> Adding Madison Chapter JSON file

chapters/belfast.json
JSON file with details of the Belfast chapter and organisers
=> Belfast chapter

chapters/london.json
Added @ezodude as an organiser as instructed by @iancrowther .
=> ezodude added as an organiser.

chapters/columbus.json
JSON file with details of the Columbus, OH chapter
=> columbus json

index.html
add meanworks: automated workshop on MEAN stack with angular full stack generator and series of videos to give an overview of the MEAN stack and the workshop tool
- Tool: https://github.com/azat-co/meanworks
- Playlist: https://www.youtube.com/playlist?list=PLguYmmjtxbWEdBy8FqGcz7ZIdl0cHV9SY
- Slides: https://github.com/azat-co/meanworks/blob/master/slides/README.pdf
=> add meanworks

index.html, languages/ru.json, languages/uk.json
I've made a workshopper about using the terminal and Bash. Check out [learnyoubash](https://github.com/denysdovhan/learnyoubash)!
=> Add learnyoubash workshopper

index.html
I've added "Seneca in practice" workshop to the homepage workshop list.
=> Add seneca workshop link

index.html
Fixed i18n tag for seneca-in-practice workshop.
=> Fixed issue #475

chapters/foyle.json
created foyle.json file for http://nodeschool.io/foyle-valley/ chapter
=> Created foyle.json

chapters/bratislava.json, hexdex.html, images/nodeschool-bratislava.svg
=> #330 add bratislava hexagon and to chapters 

index.html
=> moving ga token into header to comply with google site verification

chapters/vellore.json
Added the JSON data for Vellore NodeSchool.
=> Vellore NodeSchool added

languages/vi.json
Added `workshopper-how-to-markdown` translation.
=> Add workshopper-how-to-markdown

chapters/montreal.json
Depends on nodeschool/organizers/issues/350
@David-Ro and I will fork the nodeschool/toronto repo to get a jump start
=> Adding Montreal chapter

chapters/kikinda.json
Please review and merge, kikinda.json added for Kikinda, Serbia, as a new chapter.
=> Added Kikinda chapter JSON

chapters/chernivtsi.json
We have made a site http://nodeschool.io/chernivtsi
So here is an update.
=> Add website to Chernivtsi chapter.

index.html
write your the first Bash script. -> write your first Bash script.
=> Remove extra word in learnyoubash description

index.html, languages/fr-fr.json
I've built a workshopper about LESS called [`less-is-more`](https://github.com/gnerkus/less-is-more)
=> Add the 'less-is-more' workshopper

README.md
=> Update README on running locally

index.html
=> Link past events write up to repo

chapters/gurgaon.json
Added gurgaon.json file for discoverability
=> Created gurgaon json file for discoverability

index.html
This adds a workshop for learning concepts from functional (and) reactive programming using the library [Bacon.js](https://github.com/baconjs/bacon.js).
The workshop can be found at https://github.com/mikaelbr/bacon-love and tested out by doing:
```
npm i -g bacon-love
```
---
Thanks for your awesome site and curating a brilliant set of learning resources for getting into different aspects of node (and JavaScript) programming.
=> Add workshop bacon-love

chapters/sorocaba.json
=> Added Sorocaba chapter

index.html, languages/es.json
Hi all, wanted to add a relatively simple workshopper to go over [InnerSource]() via Node.
Included workshopper translation for Spanish. 
PS: we're having an Austin, TX, USA, NodeSchool meetup on 12/6/2016, and it will cover this new workshopper. 
Thx!
--Monico
=> add workshopper for innersourceadventure; translation for spanish

chapters/dusseldorf.json
pretty much what it says on the tin
=> add nodeschool düsseldorf

index.html
From https://github.com/workshopper/how-to-npm/issues/73.
=> Update the link of how-to-npm

index.html, languages/ru.json, languages/uk.json
Just adding my new workshopper: [`learnyouhtml`](https://github.com/denysdovhan/learnyouhtml)
Will be glad to move this to the workshopper org.
=> Add learnyouhtml as core workshopper

LICENSE, index.html
#209 I added a link to footer to view the the license in github. Also went out on a limb and updated the date on the copyright. I'm most definitely not a lawyer but I believe we'd want that to be current.
=> Adding link to license on footer. Updating date on copyright

CONTRIBUTING.md
As  a first time contributor, it wasn't immediately clear to me that master was only for autobuild results. I thought it would be helpful to explicitly mention the branch that pull requests should be targeting.
=> Clarifying the branch to use for contributions

scripts/build-chapters.js, scripts/build-html.js, scripts/generate-lang.js, scripts/generate-untranslated-lang.js, scripts/util/cmdwatcher.js, scripts/util/get-i18n-list.js, scripts/validate-html.js
Removing semicolons closes issue #537
=> Removed semicolons in '/scripts/' per JS Standard Style

chapters/passau.json
Hi all,
I just added the json file for making the newly founded chapter Passau appear on https://nodeschool.io/chapters.html.
Could you please check whether I added all that is to this?
Thanks and kind regards,
Valentin
=> Added chapter Passau

chapters/karachi.json
Added NodeSchool Karachi chapter in the chapters listing.
Closes #596
=> chore(chapter): added karachi chapter on the chapters listing

chapters/abuja.json
This PR is to add Abuja NodeSchool to the Chapter list
Thank You
=> Added Abuja to Chapter list

index.html
I removed the phrase "or subscribe to our free email newsletter" as they are not currently being sent out.
=> Remove email newsletter

chapters/lahore.json
http://nodeschool.io/Lahore gives error page,
=> fixed Lahore chapter url typo

chapters/sanmiguel.json
hope this fixes troubles with our team with chapters  at nodeschool.io :fire: :hear_eyes: :tada:
=> San Miguel team conf

hexdex.html
=> Add Hexdex Lima

index.html
following standard of the workshoppers
=> switch git clone to npm install for learnuv

.env.example, .gitignore, README.md, index.html, package.json, scripts/build-copy.js, scripts/build-html.js, scripts/build.sh, scripts/deploy.sh, styles/style.styl
Hi there,
I just left NodeSchool Paris where I tried a bunch of workshops. Some of them are really great, some of them... nah.
A GitHub stargazers count in front of each workshop name could add a little feedback about a workshop popularity.
What do you think ?
=> ⭐️GitHub stargazers count
