- languages/zh-cn.json
Since `learnyounoe` v2.1.0 out, all of my efforts are in the official repo(thanks to  all of the contributors for i18n), and I have made it a complete Simplified Chinese translation.
So `learnyounode-zh-cn` is needless now.
> relpace learnyounode-zh-cn to learnyounode

- about.html
The YouTube link for Jason Rhodes's talk is a private video. There is another version on YouTube that is publicly viewable. This pull request updates the link to that public link.
> update video link

- js/lang.js
The current code tracks the language code with a `data-lang` attribute on the `body` element.
For accessibility purposes, the language code should be in the `lang` attribute of the `html` element. (See http://www.w3.org/TR/WCAG20-TECHS/H57.html for details.) So this pull request moves it there.
Pre-emptive strike: Yes, ideally, the attribute should be in the static document source and not inserted dynamically with JavaScript. However, we don't have a choice here (short of rendering a different file for each language, which may not be a terrible solution actually) because there is no dynamic server side rendering. Yes, screen-readers etc. that do not handle JavaScript will not see the `lang` attribute. However, there are certainly screen-readers that do handle JavaScript, and the ratio of …
> update lang in html element attribute rather than body

- index.html
I tested this on VoiceOver to make sure it still works properly when languages are changed as well as when the page is reloaded after selecting a different language than English. It does. 
This change will slightly reduce the guesswork on the browser's part while waiting for initial page load. It will set a better example for people forking the code for their own NodeSchool instances. And it is more friendly to automated accessibility checking tools. None of these are huge wins, but they *are* small wins and it's the right thing to do.
> since default language is "en", specify it

- index.html
The alt text "nodeschoolhouse" is unintelligible to screen readers and probably other assistive technology. Since the purpose of alt text is to provide the information that would be missing in situations where the image is not available (e.g., someone using a screen reader), this particular alt text should be blank as the image is mostly decorative.
> rm confusing alt text

- events.css
- js/table.js
This should fix #225.
`table.js` was pretty out of date, this syncs the code with head of https://github.com/jlord/sheetsee-calendar, with [my latest changes](https://github.com/jlord/sheetsee-calendar/compare/5438796350e7d52def89a839f29a12c4963056ee...954d4a86b703244d62b7dbe31ba034a7cb1341e9) that are supposed to address the start date issue.
I've also made some slight CSS changes so it looks less crooked. 
There's an event in 1999, which I assume is incorrect data, maybe someone who has admin access to the spreadsheet can edit it?
**Local env screenshot**
cc @maxogden @jlord
> Fix event calendar

- about.html
- building-workshops.html
- chapters.html
- events.html
- hexdex.html
- host.html
- index.html
The `meta notranslate` tag on the NodeSchool site is used to control the translation behavior of Google's search results page. Per [Google documentation](https://support.google.com/webmasters/answer/79812?hl=en) the correct markdown for the `meta notranslate` tag uses a `content` attribute and not a `value` attribute.
This has the added minor benefit of being valid HTML5 whereas the use of a `value` attribute on the `meta` tag is not. (I only noticed this issue because I ran the site through the W3C validator.)
> replace value attribute with content attribute

- style.css
Currently, given the amount of languages, text-align right looks pretty bad. This makes it match the general center style of the site.
> Change language nav to center align

- js/main.js
Current event list is reverse chronological sorting which is (to me, at least) confusing. I expect the next event to be the first one listed, not the last one listed. This change reverses that sorting for a hopefully more intuitive listing.
> sort events chronologically

- about.html
- building-workshops.html
- chapters.html
- events.html
- hexdex.html
- host.html
- index.html
- js/lang.js
- js/main.js
- js/table.js
- style.css
Hey everyone,
this PR fixes a lot of a11y issues and especially improves the usage with screen readers.
The improvements include:
* Make NodeSchool heading readable
* Some ARIA/HTML5 mark up
* Hide map from screen readers (for now)
* [Skip to content link](http://webaim.org/techniques/skipnav/)
* Fix Heading outlines
Right now this removes the "Node's Cool" animation from the first page. Basically the problem was that this made screen readers pronounce NodeSchool like "N - O - D - E Apostrophs C - ....". I thought about fixing it, but then just removed it. Maybe someone can re-add it later in a screenreadable way.
Otherwise there are only slight visual changes to the heading sizes.
Best,
Finn
> Improve a11y

- about.html
- building-workshops.html
- chapters.html
- events.html
- hexdex.html
- host.html
- index.html
- mentor-at-event.html
`i` `s` `o` `g` `r` `a` `m` -> `s` `c` `h` `O` `o` `l`
================
The code is generated by using [isogram](https://github.com/shinnn/isogram), a well-tested Google Analytics easter egg generator used in:
* [gulpjs.com](http://gulpjs.com/) - `g` `u` `l` `p` `j` `s`
* [Jekyll website](http://jekyllrb.com/) - `j` `e` `k` `y` `l` `L`
* [cssnext website](https://cssnext.github.io/) - `c` `s` `s` `N` `e` `x` `t`
* [and so on](https://github.com/shinnn/isogram/tree/1363db298b1d9c015581094ccbe8de5f2c2ecf7f#websites-using-isogram)
If you prefer other characters, I'll update the commit. For example:
`n` `o` `d` `e` `j` `s`
```js
!function(n,o,d,e,j,s){n.GoogleAnalyticsObject=d;n[d]||(n[d]=function(){
(n[d].q=n[d].q||[]).push(arguments)});n[d].l=+new Date;j=o.createElement(e); …
```
> Renamed the variables in Google Analytics script

- js/index.js
As discussed in #337.
Have some doubts whether this code is good enough.
It's a bit fragile, because:
1) it relies on id & class selectors for containers, as well as layout to be the same (with first `.third` item to contain info only, and not track those link clicks [although we could totally track how many people are following issues link when willing to ask a question])
2) it relies on href to provide workshopperId (which would be the reponame, given all links are to github)
Would love to hear feedback and modify code accordingly.
> Add google analytics tracking for workshopper links clicks

- index.html
As this leads into the `learn-generators` workshopper, I have attempted to place
it before `learn-generators` in the page layout.
> Add esnext-generation workshopper

- index.html
new url redirects to latest version of sublime text, which is 3 instead of 2, the older version.
> link redirects to latest version of sublime text

- chapters/lyon.json
the [organisers README](https://github.com/nodeschool/organizers#3) insists on not forgetting to run `npm build` but it doesn't seem to change any tracked file, are there file in the `.build` that should be added to this PR?
> adding chapters/lyon.json

- LICENSE
- package.json
Closes #437 
I think BSD-2-Clause is the most sensible choice when choosing between the BSD SPDX licenses. If you disagree please let me know as IANAL.
I've opted for giving the copyright to "NodeSchool" - I don't know if that's correct either?
> Update license to valid SPDX license

- languages/es.json
Potential reviewers: @julianduque @theHazzard @nisnardi @jeduan 
This is part of https://github.com/nodeschool/nodeschool.github.io/issues/279
> add hexdex to spanish translation

- chapters/costarica.json
This PR pretends to update the website and organizers' information related to NodeShool Costa Rica.
FYI - @gaboesquivel
> NodeSchool Costa Rica - Organizers & Website [update]

- index.html
- languages/ru.json
- languages/uk.json
I've built a workshopper about Markdown called [`how-to-markdown`](https://github.com/denysdovhan/how-to-markdown):
@martinheidegger said [it's okay to add this to Core section](https://gitter.im/nodeschool/organizers?at=570bb9f2ddb5a2cf3bbb46f2).
> Add a how-to-markdown workshopper.

- chapters/bainbridge.json
Removing previously listed organizers and updating with current ones. Also added our website and twitter information. If needed, new organizers can be verified at our Meetup Page as well: https://www.meetup.com/IslandJS-Nodeschool/
> Update bainbridge.json with new owners and links

- chapters/vancouver.json
This PR is just some housekeeping to update the Vancouver organizers to match the [nodeschool/vancouver team](https://github.com/orgs/nodeschool/teams/vancouver).
> Update Vancouver organizers

- index.html
Running ```npm run validate-html``` reveals that the i18n tag for both bacon-love and Currying were the same.  This resulted in the improper text displaying for the bacon-love description.  This PR corrects the issue.
> corrected data-i18n tag for bacon-love workshop

- chapters/oulu.json
Registering the NodeSchool Oulu chapter on the site. No Twitter account yet unfortunately.
> Add Oulu chapter JSON file

- index.html
Node.js version 'recommended for most users' is currently v4.5.0 LTS. Workshopper menu selection bug (see Node.js issue [#5384](https://github.com/nodejs/node/issues/5384)) fixed in v6.2.0, so current version is recommended for NodeSchool users.
> Add recommended min Node.js version

- index.html
Following from PR #528, the 'minimum NodeJs version' has been rephrased to indicate the first step in troubleshooting problems. Also added a link to discussions added for further help.
> Update min recommended NodeJs text

- index.html
Noticed a typo in the title of the workshopper I added yesterday; just wanted to push a quick fix for that.
> Removed "/" from title of "JS best practices"

- index.html
Updates URL to `learn-sass` which was recently moved to the [workshopper](https://github.com/workshopper) organization but the tutorials page kept pointing at my personal repo, as pointed out by @opperbolt in https://github.com/workshopper/learn-sass/issues/43.
> Fixes URL to learn-sass moved to workshopper org

- index.html
Heyo! 🍕 
This updates the site to point to the Electron desktop version of Git-it which is the nice fun version that I'm actively maintaining ✨ 
Let me know thoughts on what to put in the space that is supposed to show how to npm install. 
_Preview_ 
_Another option that links to directly to releases page_
🔗 https://github.com/workshopper/org/issues/27
> Update Git-it info

- chapters/bengaluru.json
The Bangalore chapter name was renamed to Bengaluru. This update reflects
the change in names on the Nodeschool site.
> Update Bangalore chapter to Bengaluru

- scripts/generate-lang.js
#133 Looking at the existing translations, it seemed like the existing languages went with the first column in the referenced table.
> Updated example language code in generate-lang script

- about.html
- building-workshops.html
- chapters.html
- events.html
- footer.html
- hexdex.html
- host.html
- index.html
- mentor-at-event.html
- scripts/build-html.js
While working on #306 and #587 I realized that the footer is duplicated across all the html files. When I add the license link to the footer for #587, the license link was only added to index.html. Rather manually update the footer across all the html files, I decided to try to inject the footer as part of the build-html.js script.
Having read CONTRIBUTING.md, I realize the goal is to keep things simple. While using the build script to insert the header is less simple than having the footer duplicated, I think it's worth the extra complexity. But, if that's not the consensus, I can manually update the remaining footers to be consistent with the index.html changes made in #587 
I tested this by running "npm start" and confirmed the footer appeared. I did notice that this breaks the …
> Extracting footers to file and injecting during build-html script

- about.html
The video link doesn't work anymore, and the other one is outdated as well. I think we should just remove them. They're also all only in english and we'll not be able to keep this page updated.
> remove talks section from about

- hexdex.html
- js/chapters.js
- styles/chapters.styl
+ +Tag noscript para JS deshabilitado
+ ~Ajuste de alto y ancho de cada insignia
+ +Cantidad de Insignias por región
------
+ +tag noscript for JS disabled
+ ~adjust height and width for each badge
+ +Count of badges by region
antes/before
despues/before
#628
> HexDex Page

- languages/fr-fr.json
Translated 'Code of conduct' in the about page to Fr :
> Translated 'Code of conduct' to Fr
